- name: Setup webserver
  hosts: cdv
  become: yes
  tasks:
    - name: Install nginx on Debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
    - name: Install nginx on RHEL
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"
    - name: Start nginx
      service:
        name: nginx
        state: started
