- name: Firewall Configuration Hardening
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure ufw is installed
      apt:
        name: ufw
        state: present

    - name: Ensure iptables-persistent is not installed with ufw
      apt:
        name: iptables-persistent
        state: absent

    - name: Ensure ufw service is enabled
      systemd:
        name: ufw
        enabled: yes
        state: started
        masked: no

    - name: Enable ufw
      ufw:
        state: enabled

    - name: Allow incoming traffic on loopback interface
      ufw:
        rule: allow
        direction: in
        interface: lo

    - name: Allow outgoing traffic on loopback interface
      ufw:
        rule: allow
        direction: out
        interface: lo

    - name: Deny incoming traffic from 127.0.0.0/8
      ufw:
        rule: deny
        direction: in
        from_ip: 127.0.0.0/8

    - name: Deny incoming traffic from ::1
      ufw:
        rule: deny
        direction: in
        from_ip: ::1

    - name: Ensure ufw outbound connections are configured
      ufw:
        rule: allow
        direction: out
        to_ip: any
        port: any
        proto: any

