- name: Configure Logging
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure systemd-journald-remote is installed
      apt:
        name: systemd-journald-remote
        state: present
    - name: Ensure systemd-journal-remote is configured
      lineinfile:
        path: /etc/systemd/journal-upload.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^URL=', line: 'URL=10.0.1.6' }
        - { regexp: '^User=', line: 'User=azureuser'}
        - { regexp: '^Password=', line: 'Password=Q1w2e3r4t5y6.'}
    - name: Restart systemd-journald-remote
      systemd:
        name: systemd-journald-remote
        state: restarted


