- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  collections:
    - community.general
  tasks:
    - name: Check xserver-xorg installation status
      command: dpkg-query -l "{{ item }}"
      with_items:
        - xserver-xorg
      ignore_errors: yes
      register: xserver_installed

    - name: Display xserver-xorg status
      debug:
        msg: "xserver-xorg is {{ xserver_installed.results[0].stderr }}"


