- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  vars:
    services:
      - xserver-xorg
      - avahi-daemon
      - cups
      - isc-dhcp-server
      - slapd
      - nfs-kernel-server
      - bind9
      - vsftpd
      - apache2
      - dovecot-imapd
      - dovecot-pop3d
      - samba
      - squid
      - snmp
      - nis
      - rsync
  tasks:
    - name: Check installation status
      command: dpkg-query -l "{{ item }}"
      with_items: "{{ services }}"
      ignore_errors: yes
      register: installation_status

    - name: Display installation status for each service
      debug:
        msg: "{{ item.item }} is {{ 'installed' if item.stderr == '' else 'not installed' }}"
      with_items: "{{ installation_status.results }}"
