- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  collections:
    - community.general
  tasks:
    - name: Check xserver-xorg installation status
      dpkg_selections:
        name: xserver-xorg
        selection: install
      register: dpkg_facts

    - name: Display installed xserver-xorg packages
      debug:
        msg: "{{ item }}"
      with_items: "{{ dpkg_facts.results | selectattr('ansible_facts.dpkg_selections.status', 'equalto', 'install') | list }}"


