- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  tasks:
    - name: Check X Window System
      command: dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' xserver-xorg* | grep -Pi '\h+installed\b'
      register: x_window_chk

    - name: Display X Window System status
      debug:
        msg: "X Window System is {{ x_window_chk.stdout }}"
