- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  collections:
    - community.general
  tasks:
    - name: Check xserver-xorg installation status
      package_facts:
        manager: auto
      register: xserver_installed

    - name: Display xserver-xorg status
      debug:
        msg: "xserver-xorg is {{ xserver_installed.packages['xserver-xorg'] }}"
      when: xserver_installed is changed


