- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  tasks:
    - name: Check xserver-xorg installation status
      dpkg_selection_facts:
      register: dpkg_facts

    - name: Display installed xserver-xorg packages
      debug:
        msg: "{{ item }}"
      with_items: "{{ dpkg_facts.packages | select('match', '^xserver-xorg.*') | selectattr('status', 'equalto', 'installed') | list }}"

