- name: Install required roles
  hosts: localhost
  tasks:
    - name: Install role from Ansible Galaxy
      command: ansible-galaxy install community.general
      become: true

- name: Check Special Purpose Services hardening
  hosts: localhost
  become: yes
  collections:
    - community.general
  tasks:
    - name: Check xserver-xorg installation status
      dpkg_selections:
      register: dpkg_facts

    - name: Display installed xserver-xorg packages
      debug:
        msg: "{{ item }}"
      with_items: "{{ dpkg_facts.packages | select('match', '^xserver-xorg.*') | selectattr('status', 'equalto', 'installed') | list }}"

