- name: Harden unused FS without using scripts
  hosts: localhost
  tasks:
    - name: Disable cramfs
      mount:
        path: "{{ item }}"
        fstype: cramfs
        state: absent
      with_items:
        - /tmp
        - /var/tmp
        - /var/log
        - /var/log/audit
        - /home
        - /srv
        - /opt
        - /usr/local
        - /media
        - /mnt
        - /root
        - /boot
      register: cramfs_hardening

    - name: Disable freevxfs
      mount:
        path: /tmp
        fstype: freevxfs
        state: absent
      register: freevxfs_hardening

    - name: Disable jffs2
      mount:
        path: /tmp
        fstype: jffs2
        state: absent
      register: jffs2_hardening

    - name: Disable hfs
      mount:
        path: /tmp
        fstype: hfs
        state: absent
      register: hfs_hardening

    - name: Disable hfsplus
      mount:
        path: /tmp
        fstype: hfsplus
        state: absent
      register: hfsplus_hardening
