apiVersion: v1
kind: Pod
metadata:
  name: random-number-pod
spec:
  containers:
  - name: random-number-container
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 1-100 -n 1 >> /opt/random-number.txt;"]
    volumeMounts:
    - name: data-volume
      mountPath: /opt
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: Directory
