apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdv-fastapi-101
  labels:
    app: cdv-fastapi-101
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdv-fastapi-101
      env: dev
  template:
    metadata:
      name: cdv-fastapi-101
      labels:
        app: cdv-fastapi-101
        env: dev
    spec:
      containers:
      - name: cdv-fastapi-101
        image: cdvactionsdevacr.azurecr.io/fastapi-101:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cdv-fastapi-101
spec:
  selector:
    app: cdv-fastapi-101
    env: dev
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
