apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  labels:
    app: mailhog
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mailhog
      env: dev
  template:
    metadata:
      name: cdv-mailhog
      labels:
        app: mailhog
        env: dev
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  selector:
    app: mailhog
    env: dev
  type: LoadBalancer
  ports:
  - port: 8025
    targetPort: 8025

