apiVersion: v1
kind: Pod
metadata:
  name: cdv-redis
  labels:
    app: redis
    env: dev
spec:
  containers:
  - name: redis
    image: redis123
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
