apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: voting-app
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_vote
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: voting-app
spec:
  selector:
    name: voting-pod
    app: voting-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80


