apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: voting-app
spec:
  containers:
  - name: worker
    image: dockersamples/examplevotingapp_worker
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"

