apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pvc
  labels:
    name: postgres-container
spec:
  containers:
  - name: postgres-container
    image: postgres
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: "passowrd"
    volumeMounts:
      - name: mypv
        mountPath: /var/lib/postgresql/data
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: mypvc

