apiVersion: v1
kind: ReplicationController
metadata:
  name: mailhog-rc
  labels:
    name: mailhog-rc
    type: dev
spec:
  replicas: 3
  selector:
    app: mailhog
    env: dev
  template:
    metadata:
      name: cdv-mailhog
      labels:
        app: mailhog
        env: dev
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8025
