- name: Harden unused FS
  hosts: localhost
  become: yes
  tasks:
    - name: Disable cramfs
      mount:
        path: "{{ item }}"
        fstype: cramfs
        state: absent
      with_items:
        - /tmp
        - /var/tmp
        - /var/log
        - /var/log/audit
        - /home
        - /srv
        - /opt
        - /usr/local
        - /media
        - /mnt
        - /root
        - /boot
