- name: Harden unused FS
  hosts: localhost
  become: yes
  vars:
    paths:
      - /tmp
      - /var/tmp
      - /var/log
      - /var/log/audit
      - /home
      - /srv
      - /opt
      - /usr/local
      - /media
      - /mnt
      - /root
      - /boot
  tasks:
    - name: Disable cramfs
      mount:
        path: "{{ item }}"
        fstype: cramfs
        state: absent
      with_items: "{{ paths }}"

    - name: Disable freevsfx
      mount:
        path: "{{ item }}"
        fstype: freevsfx
        state: absent
      with_items: "{{ paths }}"

