# Benchmark for Ubuntu 22.04 LTS
- name: Configure logging for journal
  hosts: localhost
  become: yes
  tasks:
    - name: Install journal remote
      apt:
        name: systemd-journal-remote
        state: present

    - name: Configure journal-remote
      lineinfile:
        path: /etc/systemd/journal-upload.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^URL="
          line: "URL=10.0.1.4"
        - regexp: "^User="
          line: "User=azureuser"
        - regexp: "^Password="
          line: "Password=Q1w2e3r4t5y6."

    - name: Restart journal-upload
      systemd:
        name: systemd-journal-upload
        state: restarted

    - name: Enable journal-remote
      systemd:
        name: systemd-journal-upload.service
        enabled: true

    - name: Disable journal remote socked
      systemd:
        name: systemd-journal-remote.socket
        enabled: false

    # - name: Enable jounald service
    #   sys
