# CIS Benchmark for Ubuntu 20.04
- name: Time synchonization hardening
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure chrony is installed
      apt:
        name: chrony
        state: present

    - name: Purge ntp
      apt:
        name: ntp
        state: absent

    - name: Stop and mask systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: false
        masked: true

    - name: Configure chrony
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^pool ntp.ubuntu.com"
          line: "pool ntp.ubuntu.com        iburst maxsources 4"
        - regexp: "^pool 0.ubuntu.pool.ntp.org"
          line: "pool 0.ubuntu.pool.ntp.org iburst maxsources 1"
        - regexp: "^pool 1.ubuntu.pool.ntp.org"
          line: "pool 1.ubuntu.pool.ntp.org iburst maxsources 1"
        - regexp: "^pool 2.ubuntu.pool.ntp.org"
          line: "pool 2.ubuntu.pool.ntp.org iburst maxsources 2"
        - regexp: "^user"
          line: "user _chrony"

    - name: Ensure chroney is enabled
      systemd:
        name: chrony
        enabled: true

    - name: Restart chroney after configuration
      systemd:
        name: chrony
        state: restarted
