apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-autoscaling
spec:
  selector:
    matchLabels:
      app: cpu-autoscaling
      env: dev
  template:
    metadata:
      labels:
        app: cpu-autoscaling
        env: dev
    spec:
      containers:
      - name: cpu-autoscaling
        image: aimvector/application-cpu:v1.0.2
        resources:
          limits:
            memory: "50Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-autoscaling
spec:
  selector:
    app: cpu-autoscaling
    env: dev
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-autoscaling
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

