name: Build and Test Docker Container
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - "Kubernetes/fastapi-101-main/**"
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Save Docker image
        run: |
          docker save fastapi-101:latest \
          -o fastapi-101.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-image
          path: fastapi-101.tar
