name: Publish container to ACR
on:
  pull_request:
    types:
      - closed
    paths:
      - "Kubernetes/fastapi-101-main/**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Save Docker image
        run: |
          docker save fastapi-101:latest \
          -o fastapi-101.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-image
          path: fastapi-101.tar

  Push:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: fastapi-image

      - name: Load Docker image
        run: |
          docker load -i fastapi-101.tar

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_REGISTRY }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag image
        run: |
          docker tag fastapi-101:latest ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest

      - name: Push image
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest
