name: Publish container to ACR
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened
    paths:
      - "Kubernetes/fastapi-101-main/**"
  push:
    branches:
      - main
    paths:
      - "Kubernetes/fastapi-101-main/**"
      - ".github/workflows/docker-build-pr.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main
      - name: Run container
        run: docker run -d -p 8000:8000 --name fastapi-101 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_HOST=127.0.0.1 fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Query container
        run: |
          sleep 15
          echo "$(curl http://localhost:8000)"
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Shutdown container
        run: docker stop $(docker ps -q --filter ancestor=fastapi-101 )
        working-directory: ./Kubernetes/fastapi-101-main
