name: Publish container to ACR
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened
    paths:
      - "Kubernetes/fastapi-101-main/**"
      
jobs:
  publish_to_acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Build image
        run: docker build . -t fastapi-101

      
