name: Publish container to ACR
on:
  pull_request:
    types:
      - closed
    paths:
      - "Kubernetes/fastapi-101-main/**"
  push:

jobs:
  publish-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
            registry: ${{ secrets.ACR_REGISTRY }}.azurecr.io
            username: ${{ secrets.ACR_REGISTRY }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image
        run: docker build . -t ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Push image
        run: docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest
        working-directory: ./Kubernetes/fastapi-101-main
