name: Publish container to ACR
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened
    paths:
      - "Kubernetes/fastapi-101-main/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Run container
        run: docker run -d -p 8000:8000 --name fastapi-101 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_HOST=postgres fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Query container
        run: |
          sleep 15
          echo "$(curl http://localhost:8000)"
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Shutdown container
        run: docker stop $(docker ps -q --filter ancestor=fastapi-101 )
        working-directory: ./Kubernetes/fastapi-101-main
