name: Deploy frontend
on:
  pull_request:
    paths:
      - "Actions/react-app/**"
      - ".github/workflows/frontend_ci.yaml"
    types:
      - opened
      - synchronize
      - reopened
  push:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ./Actions/react-app

      - name: Test code
        run: npm run test
        working-directory: ./Actions/react-app

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ./Actions/react-app

      - name: Build frontend
        run: npm run build
        working-directory: ./Actions/react-app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: ./Actions/react-app/dist

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Output artifact
        run: ls -la

      - name: Upload files to Storage Account
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-bach --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --destination \$web --source .
