name: Test changes on Python package
on:
  pull_request:
    paths:
      - "Actions/python-package/**"
      - ".github/workflows/python_test.yaml"
    types:
      - opened
      - synchronize
      - reopened
  push:

jobs:
  Test:
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
        working-directory: ./Actions/python-package

      - name: Run tests
        run: |
          pytest tests/klarity_connector_tests.py
        working-directory: ./Actions/python-package

