name: Publish to Test PyPi
on:
  pull_request:
    paths:
      - "Actions/python-package/**"
    types:
      - closed
  push:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          pip install twine
        working-directory: ./Actions/python-package

      - name: Build package
        run: python setup.py sdist bdist_wheel
        working-directory: ./Actions/python-package

      - name: Publish package
        env:
          TWINE_USERNAME: _token_
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: twine upload --repository testpyip dist/*
        working-directory: ./Actions/python-package
