name: Deploy infrastructure

on:
  pull_request:
    paths:
      - "Terraform/**"
    types:
      - closed

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      application: ${{ vars.application }}
      owner: ${{ vars.owner }}
      location: ${{ vars.location }}
      prefix: ${{ vars.prefix }}
      admin_password: ${{ secrets.ADMIN_PASSWORD }}
      environment: ${{ vars.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: ./Terraform

      - name: Terraform init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform validate
        run: terraform validate
        working-directory: ./Terraform

      - name: Terraform plan
        run: |
          terraform plan \
          --var="application=${{ env.application }}" \
          --var="environments=[\"dev\", \"test\"]" \
          --var="owner=${{ env.owner }}" \
          --var="location=${{ env.location }}" \
          --var="prefix=${{ env.prefix }}" \
          --var="admin_password=${{ env.admin_password }}" \
          --var="environment=${{ env.environment }}" \
          --out=tfplan
        working-directory: ./Terraform

      - name: Terraform apply
        run: terraform apply tfplan
        working-directory: ./Terraform
